// Hand-authored pixel sprites for Sam and Stella.
// Each frame is an 18x20 grid of palette keys; '.' is transparent.
// Edit a frame by editing its rows -- widths must stay at 18 characters.

export const SPRITE_W = 18;
export const SPRITE_H = 20;

/** Palette key -> colour. */
export const SPRITE_PALETTE: Record<string, string | null> = {
  '.':  null,
  'k':  '#15120f',
  'K':  '#26221e',
  'H':  '#443d36',
  'W':  '#f6f0e2',
  'w':  '#d3c8b2',
  'E':  '#b9cc6b',
  'e':  '#8a9c4c',
  'p':  '#141208',
  'N':  '#cf918d',
  'r':  '#6d4d4a',
  'i':  '#fffaf0',
};

export const SPRITES = {
  sit: [
    '...K.........K....',
    '..KKK.......KKK...',
    '.KKrKK.....KKrKK..',
    '.KKKKKK...KKKKKKK.',
    '.KKKKKKKKKKKKKKKK.',
    '.KKEpEKKKKKEpEKK..',
    '.KKEpEKKKKKEpEKK..',
    '.KKKKKKKKKWKKKKK..',
    '..KKKWWNNWWWKKK...',
    '..KKWWWWkWWWWKK...',
    '..KKKWWWWWWWKKK...',
    '...KKWWWWWWKKK....',
    '...KKWWWWWWKKK....',
    '..KKKWWWWWWKKKK...',
    '.KKKKWWWWWWKKKKK..',
    '.KKKKWWWWWWKKKKKK.',
    '.KKKKKWWWWKKKKKKKK',
    '.KKKKKKKKKKKKKKKKK',
    '.KKWWWKKWWWKKKKKKK',
    '..kWWWkkWWWkkkkkk.',
  ],
  sitTail: [
    '...K.........K....',
    '..KKK.......KKK...',
    '.KKrKK.....KKrKK..',
    '.KKKKKK...KKKKKKK.',
    '.KKKKKKKKKKKKKKKK.',
    '.KKEpEKKKKKEpEKK..',
    '.KKEpEKKKKKEpEKK..',
    '.KKKKKKKKKWKKKKK..',
    '..KKKWWNNWWWKKK...',
    '..KKWWWWkWWWWKK...',
    '..KKKWWWWWWWKKK...',
    '...KKWWWWWWKKK..KK',
    '...KKWWWWWWKKK.KK.',
    '..KKKWWWWWWKKKKK..',
    '.KKKKWWWWWWKKKKK..',
    '.KKKKWWWWWWKKKKKK.',
    '.KKKKKWWWWKKKKKKK.',
    '.KKKKKKKKKKKKKKKK.',
    '.KKWWWKKWWWKKKKKK.',
    '..kWWWkkWWWkkkkk..',
  ],
  sitSide: [
    '..........K...K...',
    '.........KKK.KKK..',
    '........KKHKKKHKK.',
    '........KKKKKKKKK.',
    '........KKKKKKKKKK',
    '........KKKKEpEKKK',
    '........KKKKEpEKKK',
    '.......KKKKKKKKWWW',
    '......KKKKKKKKWNWW',
    '.....KKKKKKKKKWWWW',
    '....KKKKKKKKKKWWW.',
    '...KKKKKKKKKKWWWW.',
    '..KKKKKKKKKKKWWWW.',
    '..KKKKKKKKKKKWWWW.',
    '..KKKKKKKKKKKWWWW.',
    '.KKKKKKKKKKKKWWWW.',
    '.KKKKKKKKKKKKWWWW.',
    '.KKKKKKKKKKKKWWWW.',
    '.KKKWWWWKKKWWWWWW.',
    '..kkWWWWkkkWWWWk..',
  ],
  walk1: [
    '..................',
    '..................',
    '..................',
    '..........K...K...',
    '..KK.....KKHKKKHKK',
    '..KK.....KKKKKKKKK',
    '..KKK..KKKKKKKKKKK',
    '..KKKKKKKKKKEpEKKK',
    '.KKKKKKKKKKKEpEKKK',
    '.KKKKKKKKKKKKKKWWW',
    '.KKKKKKKKKKKKKWNWW',
    '.KKKKKKKKKKKKKWWWW',
    '..KKKKKKKKKKKKWWW.',
    '..KKKKKKKKKKKKWWW.',
    '...KK.kk....KK.kk.',
    '...KK.kk....KK.kk.',
    '...WW.ww....WW.ww.',
    '..................',
    '..................',
    '..................',
  ],
  walk2: [
    '..................',
    '..................',
    '..................',
    '..........K...K...',
    '..KK.....KKHKKKHKK',
    '..KK.....KKKKKKKKK',
    '..KKK..KKKKKKKKKKK',
    '..KKKKKKKKKKEpEKKK',
    '.KKKKKKKKKKKEpEKKK',
    '.KKKKKKKKKKKKKKWWW',
    '.KKKKKKKKKKKKKWNWW',
    '.KKKKKKKKKKKKKWWWW',
    '..KKKKKKKKKKKKWWW.',
    '..KKKKKKKKKKKKWWW.',
    '....KKk......KKk..',
    '....KKk......KKk..',
    '....WWw......WWw..',
    '..................',
    '..................',
    '..................',
  ],
  walk3: [
    '..................',
    '..................',
    '..................',
    '..........K...K...',
    '..KK.....KKHKKKHKK',
    '..KK.....KKKKKKKKK',
    '..KKK..KKKKKKKKKKK',
    '..KKKKKKKKKKEpEKKK',
    '.KKKKKKKKKKKEpEKKK',
    '.KKKKKKKKKKKKKKWWW',
    '.KKKKKKKKKKKKKWNWW',
    '.KKKKKKKKKKKKKWWWW',
    '..KKKKKKKKKKKKWWW.',
    '..KKKKKKKKKKKKWWW.',
    '...kk.KK....kk.KK.',
    '...kk.KK....kk.KK.',
    '...ww.WW....ww.WW.',
    '..................',
    '..................',
    '..................',
  ],
  walk4: [
    '..................',
    '..................',
    '..................',
    '..........K...K...',
    '..KK.....KKHKKKHKK',
    '..KK.....KKKKKKKKK',
    '..KKK..KKKKKKKKKKK',
    '..KKKKKKKKKKEpEKKK',
    '.KKKKKKKKKKKEpEKKK',
    '.KKKKKKKKKKKKKKWWW',
    '.KKKKKKKKKKKKKWNWW',
    '.KKKKKKKKKKKKKWWWW',
    '..KKKKKKKKKKKKWWW.',
    '..KKKKKKKKKKKKWWW.',
    '....KKk......KKk..',
    '....KKk......KKk..',
    '....WWw......WWw..',
    '..................',
    '..................',
    '..................',
  ],
  loaf: [
    '..................',
    '..................',
    '..........K...K...',
    '.........KKK.KKK..',
    '........KKHKKKHKK.',
    '....KKKKKKKKKKKKK.',
    '..KKKKKKKKKKKKKKKK',
    '.KKKKKKKKKKKEpEKKK',
    '.KKKKKKKKKKKEpEKKK',
    'KKKKKKKKKKKKKKKWWW',
    'KKKKKKKKKKKKKKWNWW',
    'KKKKKKKKKKKKKWWWWW',
    'KKKKKKKKKKKKKWWWWW',
    '.KKKKKKKKKKKKWWWW.',
    '.KKKKKKKKKKKWWWWW.',
    '.KKKKKKKKKKKWWWWW.',
    '..kkkWWkkkkWWWWk..',
    '..................',
    '..................',
    '..................',
  ],
  sleep: [
    '..................',
    '..................',
    '..................',
    '..................',
    '.......KKKKK..K.K.',
    '.....KKKKKKKKKKKKK',
    '...KKKKKKKKKKKHKHK',
    '..KKKKKKKKKKKKKKKK',
    '.KKKKKKKKKKKKKKKKK',
    'KKKKKKKKKKKKkkKKKK',
    'KKKKKKKKKKKKKKKWWW',
    'KKKKKKKKKKKKKWWWWW',
    '.KKKKKKKKKKKWWWWW.',
    '.KKKKKKKKKKKWWWW..',
    '..KKKKKKKKKWWWW...',
    '...kkkkkkkkkkk....',
    '..................',
    '..................',
    '..................',
    '..................',
  ],
  stretch: [
    '..................',
    '..................',
    '..................',
    '...KK.............',
    '...KK.....K...K...',
    '...KKKK..KKK.KKK..',
    '..KKKKKKKKHKKKHKK.',
    '..KKKKKKKKKKKKKKK.',
    '..KKKKKKKKKKEpEKKK',
    '...KKKKKKKKKEpEKKK',
    '...KKKKKKKKKKKKWWW',
    '...KKKKKKKKKKKWNWW',
    '...KKKKKKKKKKWWWWW',
    '...KKKKKKKKKWWWWW.',
    '..KK..KKKKWWWWWW..',
    '..KK...KKWWWW.....',
    '..WW....kkkk......',
    '..................',
    '..................',
    '..................',
  ],
  boxPeek: [
    '...K.........K....',
    '..KKK.......KKK...',
    '.KKrKK.....KKrKK..',
    '.KKKKKK...KKKKKKK.',
    '.KKKKKKKKKKKKKKKK.',
    '.KKEpEKKKKKEpEKK..',
    '.KKEpEKKKKKEpEKK..',
    '.KKKKKKKKKWKKKKK..',
    '..KKKWWNNWWWKKK...',
    '..KKWWWWkWWWWKK...',
    '..KKKWWWWWWWKKK...',
    '...KKWWWWWWKKK....',
    '...KKWWWWWWKKK....',
    '..................',
    '..................',
    '..................',
    '..................',
    '..................',
    '..................',
    '..................',
  ],
  boxIn: [
    '..................',
    '..................',
    '..................',
    '..................',
    '...K.........K....',
    '..KKK.......KKK...',
    '.KKrKK.....KKrKK..',
    '.KKKKKK...KKKKKKK.',
    '.KKKKKKKKKKKKKKKK.',
    '.KKEpEKKKKKEpEKK..',
    '.KKEpEKKKKKEpEKK..',
    '..................',
    '..................',
    '..................',
    '..................',
    '..................',
    '..................',
    '..................',
    '..................',
    '..................',
  ],
  stellaLoaf: [
    '..................',
    '..................',
    '..........K...K...',
    '.........KKK.KKK..',
    '........KKHKKKHKK.',
    '....KKKKKKKKKKKKK.',
    '..KKKKKKKKKKKKKKKK',
    '.KKKKKKKKKKKEpEKKK',
    '.KKKKKKKKKKKEpEKKK',
    'KKKKKKKKKKKKKKKKKK',
    'KKKKKKKKKKKKKKNKKK',
    'KKKKKKKKKKKKKKKKKK',
    'KKKKKKKKKKKKKKKKKK',
    '.KKKKKKKKKKKKKKKK.',
    '.KKKKKKKKKKKKKKKK.',
    '..KKKKKKKKKKKKKKK.',
    '...kkkkkkkkkkkkk..',
    '..................',
    '..................',
    '..................',
  ],
  stellaSleep: [
    '..................',
    '..................',
    '..................',
    '..................',
    '.......KKKKK..K.K.',
    '.....KKKKKKKKKKKKK',
    '...KKKKKKKKKKKHKHK',
    '..KKKKKKKKKKKKKKKK',
    '.KKKKKKKKKKKKKKKKK',
    'KKKKKKKKKKKKkkKKKK',
    'KKKKKKKKKKKKKKKNKK',
    'KKKKKKKKKKKKKKKKKK',
    '.KKKKKKKKKKKKKKKK.',
    '.KKKKKKKKKKKKKKK..',
    '..KKKKKKKKKKKKK...',
    '...kkkkkkkkkkk....',
    '..................',
    '..................',
    '..................',
    '..................',
  ],
} as const;

export type SpriteName = keyof typeof SPRITES;
